//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_ImaginaPay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCIONES
    {
        public long ID_TRANSACCION { get; set; }
        public decimal TOTAL_TRANSACCION { get; set; }
        public System.DateTime FECHA_TRANSACCION { get; set; }
        public string USUARIO_RUT { get; set; }
    }
}
